sudo: required
language: generic
services:
 - docker
before_install:
 - docker build -t suhasappa/react-test -f ./client/Dockerfile.dev .

script:
 - docker run -e CI=true suhasappa/react-test npm test

after_success:
 - docker build -t suhasappa/multi-client ./client
 - docker build -t suhasappa/multi-nginx ./nginx
 - docker build -t suhasappa/multi-server ./server
 - docker build -t suhasappa/multi-worker ./worker
 #Login to docker CLI
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take the images and push to docker hub
 - docker push suhasappa/multi-client
 - docker push suhasappa/multi-nginx
 - docker push suhasappa/multi-server
 - docker push suhasappa/multi-worker
deploy: 
 provider: elasticbeanstalk
 region: "us-east-1"
 app: "docker-react"
 env: "Dockerreact-env"
 bucket_name: "elasticbeanstalk-us-east-1-253828931267"
 bucket_path: "docker-react"
 on: 
  branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key: $AWS_SECRET_KEY
